BOARD_TAG    = mega2560
MONITOR_PORT = /dev/ttyACM*
ARDUINO_LIBS = SPI

AVR_TOOLS_DIR = /usr
ARDUINO_DIR   = /usr/share/arduino
#ARDMK_DIR     = /usr/local

#include /usr/share/arduino/Arduino.mk
include Arduino.mk
